# 389. Find the Difference
# Easy
#
#    You are given two strings s and t.
#
#    String t is generated by random shuffling string s and then add one more letter at a random position.
#
#    Return the letter that was added to t.
#
#
#
#    Example 1:
#
#    Input: s = "abcd", t = "abcde"
#    Output: "e"
#    Explanation: 'e' is the letter that was added.
#
#    Example 2:
#
#    Input: s = "", t = "y"
#    Output: "y"
#
#
#
#    Constraints:
#
#        0 <= s.length <= 1000
#        t.length == s.length + 1
#        s and t consist of lowercase English letters.
#

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        if len(s) < len(t):
            return Solution.find(t, s)
        return Solution.find(s, t)

    def find(longStr, shortStr):
        charMap = Solution.countChars(shortStr)

        for ch in longStr:
            if ch in charMap:
                charMap[ch] -= 1
                if charMap[ch] < 0:
                    return ch
            else:
                return ch


    def countChars(s):
        charMap = {}
        for ch in s:
            charMap[ch] = charMap.setdefault(ch,0) + 1
        return charMap


